cmd_/root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/flow_dissector.o := gcc -Wp,-MD,/root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/.flow_dissector.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include -I/root/163/openvswitch-2.3.1-allinone-icmp/include -I/root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/compat -I/root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/compat/include -I/usr/src/kernels/3.10.0-123.13.2.el7.x86_64/arch/x86/include -Iarch/x86/include/generated  -Iinclude -I/usr/src/kernels/3.10.0-123.13.2.el7.x86_64/arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I/usr/src/kernels/3.10.0-123.13.2.el7.x86_64/include/uapi -Iinclude/generated/uapi -include /usr/src/kernels/3.10.0-123.13.2.el7.x86_64/include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -m64 -mno-sse -mpreferred-stack-boundary=3 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -pg -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DVERSION=\"2.3.1\" -I/root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/.. -I/root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/.. -g -include /root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/kcompat.h  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(flow_dissector)"  -D"KBUILD_MODNAME=KBUILD_STR(openvswitch)" -c -o /root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/.tmp_flow_dissector.o /root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/flow_dissector.c

source_/root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/flow_dissector.o := /root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/flow_dissector.c

deps_/root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/flow_dissector.o := \
  /root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/kcompat.h \
  include/generated/uapi/linux/version.h \

/root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/flow_dissector.o: $(deps_/root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/flow_dissector.o)

$(deps_/root/163/openvswitch-2.3.1-allinone-icmp/datapath/linux/flow_dissector.o):
